/* ===================== WORD BANK ===================== */
const wordBank = {
  "Animaux": [["dog","chien"],["cat","chat"],["bird","oiseau"],["horse","cheval"],["cow","vache"],["pig","cochon"]],
  "Cuisine": [["knife","couteau"],["fork","fourchette"],["spoon","cuillère"],["plate","assiette"],["cup","tasse"],["pan","poêle"]],
  "Sport": [["football","football"],["tennis","tennis"],["swim","nager"],["run","courir"],["jump","sauter"],["gym","salle de sport"]],
  "Vêtements": [["shirt","chemise"],["pants","pantalon"],["dress","robe"],["skirt","jupe"],["shoes","chaussures"],["socks","chaussettes"]],
  "Couleurs":[["red","rouge"],["blue","bleu"],["green","vert"],["yellow","jaune"],["black","noir"],["white","blanc"]],
  "Fruits":[["apple","pomme"],["banana","banane"],["orange","orange"],["grape","raisin"],["pear","poire"],["strawberry","fraise"]],
  "École":[["school","école"],["book","livre"],["pen","stylo"],["pencil","crayon"],["teacher","professeur"],["student","étudiant"]],
  "Maison":[["house","maison"],["door","porte"],["window","fenêtre"],["table","table"],["chair","chaise"],["bed","lit"]],
  "Métiers":[["doctor","médecin"],["nurse","infirmière"],["teacher","enseignant"],["engineer","ingénieur"],["driver","chauffeur"],["chef","chef"]],
  "Transports":[["car","voiture"],["bus","bus"],["train","train"],["plane","avion"],["bicycle","vélo"],["boat","bateau"]],
  "Technologie":[["computer","ordinateur"],["phone","téléphone"],["tablet","tablette"],["keyboard","clavier"],["mouse","souris"],["screen","écran"]],
  "Corps":[["head","tête"],["arm","bras"],["leg","jambe"],["hand","main"],["foot","pied"],["eye","œil"]],
  "Famille":[["mother","mère"],["father","père"],["brother","frère"],["sister","sœur"],["grandmother","grand-mère"],["grandfather","grand-père"]],
  "Nature":[["tree","arbre"],["flower","fleur"],["river","rivière"],["mountain","montagne"],["sea","mer"],["sky","ciel"]],
  "Météo":[["sunny","ensoleillé"],["rainy","pluvieux"],["cloudy","nuageux"],["snowy","enneigé"],["windy","venteux"],["stormy","orageux"]],
  "Animaux marins":[["fish","poisson"],["shark","requin"],["whale","baleine"],["dolphin","dauphin"],["crab","crabe"],["octopus","pieuvre"]],
  "Véhicules":[["car","voiture"],["motorbike","moto"],["truck","camion"],["bicycle","vélo"],["train","train"],["plane","avion"]],
  "Musique":[["song","chanson"],["guitar","guitare"],["piano","piano"],["drum","batterie"],["violin","violon"],["voice","voix"]],
  "Lieux":[["park","parc"],["school","école"],["cinema","cinéma"],["museum","musée"],["beach","plage"],["restaurant","restaurant"]],
  "Vêtements d’hiver":[["coat","manteau"],["scarf","écharpe"],["gloves","gants"],["hat","chapeau"],["boots","bottes"],["sweater","pull"]],
  "Vêtements d’été":[["t-shirt","t-shirt"],["shorts","short"],["sandals","sandales"],["cap","casquette"],["dress","robe"],["sunglasses","lunettes"]],
  "Loisirs":[["reading","lecture"],["painting","peinture"],["swimming","natation"],["hiking","randonnée"],["gaming","jeu vidéo"],["cycling","cyclisme"]],
  "Émotions":[["happy","heureux"],["sad","triste"],["angry","en colère"],["scared","effrayé"],["surprised","surpris"],["tired","fatigué"]],
  "Aliments":[["bread","pain"],["milk","lait"],["cheese","fromage"],["rice","riz"],["egg","œuf"],["fish","poisson"]],
  "Boissons":[["water","eau"],["juice","jus"],["milk","lait"],["coffee","café"],["tea","thé"],["soda","soda"]],
  "Objets":[["book","livre"],["pen","stylo"],["phone","téléphone"],["key","clé"],["bag","sac"],["watch","montre"]],
  "Villes":[["Paris","Paris"],["London","Londres"],["New York","New York"],["Tokyo","Tokyo"],["Berlin","Berlin"],["Madrid","Madrid"]],
  "Adjectifs":[["big","grand"],["small","petit"],["fast","rapide"],["slow","lent"],["hot","chaud"],["cold","froid"]],
  "Verbes":[["eat","manger"],["drink","boire"],["sleep","dormir"],["run","courir"],["jump","sauter"],["write","écrire"]],
  "Choses de tous les jours":[["table","table"],["chair","chaise"],["window","fenêtre"],["door","porte"],["floor
